"""A `code_fix` tool, so a fix can be asked for in the chat.

Until now a checkout-based fix only happened one way: the PR monitor decided a
review said NEEDS_FIX and called :func:`attempt_code_fix` itself. Asking for one
in the chat was not possible. The chat agent has the GitHub tools, so it could
replace a whole file through the Contents API from content it regenerated by
hand -- which is the path `workspace.py` exists to avoid, because it cannot
grep, cannot touch three files, and cannot validate before committing.

**Why a tool that delegates, rather than giving the chat itself a workspace.**
A worktree is checked out on one branch and lives for one run. A chat is a
sequence of runs that does not know, when it starts, whether it is about a PR at
all -- so attaching a workspace up front means checking out a branch nobody
named, on every message, including "why is jellyfin restarting". Opening one
mid-conversation instead would mean carrying a checkout across turns of a
WebSocket whose lifetime is a browser tab.

Delegating sidesteps all of that: the chat stays stateless, the nested run gets
a fresh context and the model configured for `code_fix` rather than for chat,
and the checkout exists for exactly as long as the fix does.

The nested run is *not* given this tool, which is what stops a fix asking for a
fix asking for a fix.
"""

from __future__ import annotations

import json
import logging
from typing import TYPE_CHECKING

from home_ops_agent.agent.core import ToolDefinition
from home_ops_agent.agent.tools import github

if TYPE_CHECKING:
    from home_ops_agent.agent.skills import SkillDefinition

logger = logging.getLogger(__name__)

# A checkout run explores before it edits -- search, read, edit, validate,
# commit -- so it needs more turns than a single-file API edit. Matches the
# budget `pr_fix` gives the same work.
MAX_TURNS = 30


async def code_fix(params: dict) -> str:
    """Fix the code on a PR's branch, in a real checkout."""
    from home_ops_agent.agent.core import Agent
    from home_ops_agent.agent.models import get_model_for_task
    from home_ops_agent.agent.prompts import get_prompt
    from home_ops_agent.agent.workspace import WORKSPACE_TASK, maybe_workspace
    from home_ops_agent.auth.credentials import build_credentials
    from home_ops_agent.config import settings

    if error := github.repo_configured():
        return error
    if not settings.github_token:
        return json.dumps({"error": "No GitHub token configured; a fix cannot be pushed."})

    try:
        pr_number = int(params["pr_number"])
    except (KeyError, TypeError, ValueError):
        return json.dumps({"error": "pr_number must be a PR number."})

    instructions = (params.get("instructions") or "").strip()

    try:
        pr = json.loads(await github.get_pr({"pr_number": pr_number}))
    except Exception as exc:
        logger.exception("code_fix: could not read PR #%s", pr_number)
        return json.dumps({"error": f"Could not read PR #{pr_number}: {exc}"})
    if pr.get("error"):
        return json.dumps(pr)

    branch = pr.get("head_ref") or ""
    if pr.get("state") != "open":
        # Pushing to a merged or closed PR's branch is almost never what was
        # meant, and is confusing to undo.
        return json.dumps({"error": f"PR #{pr_number} is {pr.get('state')}, not open."})

    model = await get_model_for_task("code_fix")

    async with maybe_workspace(model, branch) as ws:
        if ws is None:
            # Deliberately a refusal rather than a quiet fall back to the
            # single-file API path. In the PR monitor that fallback is right --
            # something is better than nothing on a run nobody is watching. Here
            # a person asked, and is owed the reason.
            return json.dumps(
                {
                    "error": (
                        f"Could not open a checkout for branch '{branch}'. The model "
                        f"assigned to code_fix ({model}) may not support one, or the "
                        "checkout failed — see the agent logs."
                    )
                }
            )

        agent = Agent(await build_credentials())
        # The GitHub tools, so the run can read the diff and comment when the
        # backend has them. Not this tool: a fix must not start another fix.
        agent.register_tools(github.get_github_tools())

        task = WORKSPACE_TASK
        if instructions:
            task = f"{task}\n\nThe person asking added:\n{instructions}"

        result = await agent.run(
            system_prompt=await get_prompt("code_fix"),
            messages=[
                {
                    "role": "user",
                    "content": (
                        f"Fix PR #{pr_number}.\n\n"
                        f"Title: {pr.get('title')}\n"
                        f"Author: {pr.get('author')}\n"
                        f"Branch: {branch}\n"
                        f"URL: {pr.get('html_url', '')}\n\n" + task
                    ),
                }
            ],
            model=model,
            max_turns=MAX_TURNS,
            workspace=ws,
        )

    return json.dumps(
        {
            "pr": pr_number,
            "branch": branch,
            "model": model,
            # The caller is another model, which will summarise this for the
            # person. The tools used are included because "did it actually
            # commit" is the first thing anyone asks, and workspace_commit
            # appearing here is the answer.
            "tools_used": [t.get("tool") for t in result.tool_calls],
            "result": result.response,
        }
    )


def _get_tools(config: dict) -> list[ToolDefinition]:
    return [
        ToolDefinition(
            name="code_fix",
            description=(
                "Fix the code on an open PR's branch, in a real git checkout. Use this "
                "when asked to fix a PR — for example a Renovate PR with a breaking "
                "change. It checks the branch out, searches the repository, edits as "
                "many files as the fix needs, validates the manifests and pushes one "
                "commit. Only files under kubernetes/apps/ can be committed. This runs "
                "a full agent and takes a while; call it once and report what it says."
            ),
            input_schema={
                "type": "object",
                "properties": {
                    "pr_number": {
                        "type": "integer",
                        "description": "The open PR to fix.",
                    },
                    "instructions": {
                        "type": "string",
                        "description": (
                            "Anything specific the person asked for. Optional — without "
                            "it the fix works from the PR itself."
                        ),
                    },
                },
                "required": ["pr_number"],
            },
            handler=code_fix,
        )
    ]


def _make_skill() -> SkillDefinition:
    from home_ops_agent.agent.skills import SkillDefinition

    return SkillDefinition(
        id="code_fix",
        name="Code Fix",
        description=(
            "Lets you ask, in the chat, for a PR to be fixed. Checks the branch out,"
            " edits as many files as the fix needs, validates and pushes one commit."
            " Requires a GitHub token and a model that supports a checkout."
        ),
        builtin=False,
        get_tools=_get_tools,
    )


SKILL: SkillDefinition = _make_skill()
